MvcUI/Controllers/BrandsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Business.Models;
using Business.Services.Bases;
using Core.Business.Models.Results;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataAccess.EntityFramework.Contexts;
using Entities.Concrete;

namespace MvcUI.Controllers
{
    public class BrandsController : Controller
    {
        private readonly CarRentalContext _context;
        private readonly IBrandService _brandService;
        private readonly ICarService _carService;

        public BrandsController( IBrandService brandService, ICarService carService)
        {
            _brandService = brandService;
            _carService = carService;
        }

        // GET: Brands
        public IActionResult Index()
        {
            var model = _brandService.Query().ToList();
            return View(model);
        }

        

        // GET: Brands/Create
        public IActionResult Create()
        {
            var model = new BrandModel();
            return View(model);
        }

        // POST: Brands/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(BrandModel brand)
        {
            if (ModelState.IsValid)
            {
                var result = _brandService.Add(brand);
                if (result.Status==ResultStatus.Exception)
                {
                    throw new Exception(result.Message);
                }

                if (result.Status== ResultStatus.Success)
                {
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("",result.Message);
            }

            return View(brand);
        }

        // GET: Brands/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }
            var brandResult = _brandService.GetBrand(id.Value);
            if (brandResult.Status == ResultStatus.Exception)
            {
                throw new Exception(brandResult.Message);
            }

            if (brandResult.Status == ResultStatus.Error)
            {
                ModelState.AddModelError("", brandResult.Message);

            }

            return View(brandResult.Data);

        }

        // POST: Brands/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(BrandModel brand)
        {



            var brandResult = _brandService.Update(brand);
            if (brandResult.Status == ResultStatus.Exception)
            {
                throw new Exception(brandResult.Message);
            }

            if (brandResult.Status == ResultStatus.Success)
            {
                return RedirectToAction(nameof(Index));
            }
            ModelState.AddModelError("", brandResult.Message);
            return View(brand);
        }

        // GET: Brands/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var brandResult = _brandService.Delete(id.Value);
            if (brandResult.Status == ResultStatus.Exception)
            {
                throw new Exception(brandResult.Message);
            }

            return RedirectToAction(nameof(Index));
        }

        

       
    }
}

MvcUI/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Business.Models;
using Business.Services.Bases;
using Core.Business.Models.Results;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataAccess.EntityFramework.Contexts;
using Entities.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using MvcUI.Settings;

namespace MvcUI.Controllers
{
    [Authorize]
    public class CarsController : Controller
    {

        private readonly ICarService _carService;
        private readonly IColorService _colorService;
        private readonly IBrandService _brandService;

        public CarsController(ICarService carService, IColorService colorService, IBrandService brandService)
        {
            _carService = carService;
            _colorService = colorService;
            _brandService = brandService;
        }

        // GET: Cars
        [AllowAnonymous]
        public IActionResult Index()
        {
            var model = _carService.Query().ToList();
            return View(model);
        }
        [Authorize(Roles = "Admin,User")]
        // GET: Cars/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var car = _carService.Query().SingleOrDefault(c => c.Id == id.Value);
            if (car == null)
            {
                return View("NotFound");
            }

            return View(car);
        }
        [Authorize(Roles = "Admin")]
        // GET: Cars/Create
        public IActionResult Create()
        {
            ViewBag.Brands = new SelectList(_brandService.Query().ToList(), "Id", "Name");
            ViewBag.Colors = new SelectList(_colorService.Query().ToList(), "Id", "Name");
            var model = new CarModel();
            return View(model);
        }
        [Authorize(Roles = "Admin")]
        // POST: Cars/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CarModel car, IFormFile image)
        {
            if (ModelState.IsValid)
            {
                string fileName = null;
                string fileExtension = null;
                string filePath = null;
                bool saveFile = false;
                if (image != null && image.Length > 0)
                {
                    fileName = image.FileName;
                    fileExtension = Path.GetExtension(fileName);
                    string[] appSettingsFileExtensions = AppSettings.AcceptedImageExtensions.Split(',');
                    bool acceptedFileExtension = false;
                    foreach (var appSettingsFileExtension in appSettingsFileExtensions)
                    {
                        if (fileExtension.ToLower() == appSettingsFileExtension.Trim().ToLower())
                        {
                            acceptedFileExtension = true;
                            break;
                        }
                    }

                    if (!acceptedFileExtension)
                    {
                        ModelState.AddModelError("", "The accepted image extensions are " + AppSettings.AcceptedImageExtensions);
                        return View(car);
                    }

                    var acceptedFileLength = AppSettings.AcceptedImageMaximumLength * Math.Pow(1024, 2);
                    if (image.Length > acceptedFileLength)
                    {
                        ModelState.AddModelError("", "Maximum file size must be " + AppSettings.AcceptedImageMaximumLength + " MB");
                        return View(car);
                    }

                    saveFile = true;

                }

                if (saveFile)
                {
                    fileName = Guid.NewGuid() + fileExtension;
                    filePath = Path.Combine("wwwroot", "files", "cars", fileName);
                }

                car.ImagePath = fileName;
                var result = _carService.Add(car);
                if (result.Status == ResultStatus.Exception)
                {
                    throw new Exception(result.Message);
                }
                if (result.Status == ResultStatus.Success)
                {
                    if (saveFile)
                    {

                        using (FileStream fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            image.CopyTo(fileStream);
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", result.Message);


            }
            ViewBag.Brands = new SelectList(_brandService.Query().ToList(), "Id", "Name", car.BrandId);
            ViewBag.Colors = new SelectList(_colorService.Query().ToList(), "Id", "Name", car.ColorId);
            return View(car);
        }
        [Authorize(Roles = "Admin")]
        // GET: Cars/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var carResult = _carService.GetCar(id.Value);
            if (carResult.Status == ResultStatus.Exception)
            {
                throw new Exception(carResult.Message);
            }

            if (carResult.Status == ResultStatus.Error)
            {
                ModelState.AddModelError("", carResult.Message);

            }
            ViewBag.Brands = new SelectList(_brandService.Query().ToList(), "Id", "Name", carResult.Data.BrandId);
            ViewBag.Colors = new SelectList(_colorService.Query().ToList(), "Id", "Name", carResult.Data.ColorId);
            return View(carResult.Data);

        }
        [Authorize(Roles = "Admin")]
        // POST: Cars/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CarModel car, IFormFile image)
        {
            if (ModelState.IsValid)
            {
                string fileName = null;
                string fileExtension = null;
                string filePath = null;
                bool saveFile = false;
                if (image != null && image.Length > 0)
                {
                    fileName = image.FileName;
                    fileExtension = Path.GetExtension(fileName);
                    string[] appSettingsFileExtensions = AppSettings.AcceptedImageExtensions.Split(',');
                    bool acceptedFileExtension = false;
                    foreach (var appSettingsFileExtension in appSettingsFileExtensions)
                    {
                        if (fileExtension.ToLower() == appSettingsFileExtension.Trim().ToLower())
                        {
                            acceptedFileExtension = true;
                            break;
                        }
                    }

                    if (!acceptedFileExtension)
                    {
                        ModelState.AddModelError("", "The accepted image extensions are " + AppSettings.AcceptedImageExtensions);
                        return View(car);
                    }

                    var acceptedFileLength = AppSettings.AcceptedImageMaximumLength * Math.Pow(1024, 2);
                    if (image.Length > acceptedFileLength)
                    {
                        ModelState.AddModelError("", "Maximum file size must be " + AppSettings.AcceptedImageMaximumLength + " MB");
                        return View(car);
                    }

                    saveFile = true;

                }




                var eCar = _carService.Query().SingleOrDefault(uc => uc.Id == car.Id);
                if (string.IsNullOrWhiteSpace(eCar.ImagePath) && saveFile)
                {
                    fileName = Guid.NewGuid() + fileExtension;
                }
                else
                {
                    fileName = eCar.ImagePath;
                }

                car.ImagePath = fileName;

                var carResult = _carService.Update(car);
                if (carResult.Status == ResultStatus.Exception)
                {
                    throw new Exception(carResult.Message);
                }

                if (carResult.Status == ResultStatus.Success)
                {
                    if (saveFile)
                    {
                        filePath = Path.Combine("wwwroot", "files", "cars", fileName);
                        using (FileStream fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            image.CopyTo(fileStream);
                        }

                    }
                    return RedirectToAction(nameof(Index));
                }

                ModelState.AddModelError("", carResult.Message);
            }

            ViewBag.Brands = new SelectList(_brandService.Query().ToList(), "Id", "Name", car.BrandId);
            ViewBag.Colors = new SelectList(_colorService.Query().ToList(), "Id", "Name", car.ColorId);
            return View(car);
        }

        // GET: Cars/Delete/5
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var carResult = _carService.Delete(id.Value);
            if (carResult.Status == ResultStatus.Exception)
            {

MvcUI/Controllers/RolesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Business.Models;
using Business.Services.Bases;
using Core.Business.Models.Results;

namespace MvcUI.Controllers
{
    public class RolesController : Controller
    {
        private readonly IRoleService _roleService;

        public RolesController(IRoleService roleService)
        {
            _roleService = roleService;
        }

        // GET: Roles
        public IActionResult Index()
        {
            var query = _roleService.Query();
            var model = query.ToList();
            return View(model);
        }

        // GET: Roles/Create
        public IActionResult Create()
        {
            var model = new RoleModel();
            return View(model);
        }

        // POST: Roles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(RoleModel role)
        {
            if (ModelState.IsValid)
            {
                var result = _roleService.Add(role);
                if (result.Status == ResultStatus.Success)
                {
                    return RedirectToAction(nameof(Index));
                }
                if (result.Status == ResultStatus.Error)
                {
                    ModelState.AddModelError("", result.Message);
                    return View(role);
                }
                throw new Exception(result.Message);
            }
            return View(role);
        }

        // GET: Roles/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var query = _roleService.Query();

            var role = query.SingleOrDefault(r => r.Id == id.Value);

            if (role == null)
            {
                return View("NotFound");
            }
            return View(role);
        }

        // POST: Roles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(RoleModel role)
        {
            if (ModelState.IsValid)
            {
                var result = _roleService.Update(role);
                if (result.Status == ResultStatus.Success)
                {
                    return RedirectToAction(nameof(Index));
                }

                if (result.Status == ResultStatus.Error)
                {
                    ModelState.AddModelError("", result.Message);
                    return View(role);
                }

                throw new Exception(result.Message);
            }
            return View(role);
        }

        // POST: Roles/Delete
        [HttpPost]
        public JsonResult Delete(int id)
        {
            var deleteResult = _roleService.Delete(id);
            if (deleteResult.Status == ResultStatus.Exception)
                deleteResult.Message= "An exception occured while deleting the role!";
            return Json(deleteResult.Message);
        }

        [HttpGet]
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return View("NotFound");
            }

            var query = _roleService.Query();

            var role = query.SingleOrDefault(r => r.Id == id.Value);

            if (role == null)
            {
                return View("NotFound");
            }
            return View(role);
        }
    }
}

MvcUI/Views/Shared/AccessDenied.cshtml
@{
    ViewData["Title"] = "Access Denied";
}

<h1 class="text-danger">Access Denied.</h1>
<h2 class="text-danger">You don't have access to this page.</h2>

MvcUI/Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "Not Found";
}

<h1 class="text-danger">Not Found.</h1>
<h2 class="text-danger">Record could not be found.</h2>

MvcUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Car Rental</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/main.css" rel="stylesheet" />
</head>


<body>
    <div class="wrapper">
        <nav id="sidebar">
            <div class="sidebar-header">
                <a asp-action="Index" asp-controller="Home" class="a-navbar"><h4>Car Rental</h4></a>
            </div>
            <ul class="list-unstyled components">

                <li class="nav-item">
                    <a class="a-sidebar" asp-action="Index" asp-controller="Cars"> Cars</a>
                </li>
                @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                {
                    <li class="nav-item">
                        <a class="a-sidebar" asp-action="Index" asp-controller="Brands"> Brands</a>
                    </li>
                    <li class="nav-item">
                        <a class="a-sidebar" asp-action="Index" asp-controller="Colors"> Colors</a>
                    </li>
                    <li class="nav-item">
                        <a class="a-sidebar" asp-action="Index" asp-controller="Users"> Users</a>
                    </li>
                    <li class="nav-item">
                        <a class="a-sidebar" asp-action="Index" asp-controller="Roles"> Roles</a>
                    </li>

                }
            </ul>

        </nav>
        <div id="content">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="#" id="sidebarCollapse" class="a-navbar" title="Close Menu">
                            <i class="fas fa-list-alt"></i>
                            <i id="i-collapse" class="fas fa-chevron-left"></i> Menu
                        </a>
                    </li>
                </ul>
                <button class="navbar-toggler navbar-button" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon navbar-span"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            @if(User.Identity.IsAuthenticated && User.IsInRole("User")) { 
                                <a class="a-navbar" asp-action="Index" asp-controller="Rentals">Rental</a>
                            }
                        </li>
                    </ul>
                    <div class="navbar-text">
                        <ul class="navbar-nav mr-auto">
                            @if (!User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="a-navbar" asp-action="Register" asp-controller="Accounts"> Register</a>
                                </li>
                                <li class="nav-item">
                                    <a class="a-navbar" asp-action="Login" asp-controller="Accounts"> Login</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <div class="div-navbar">
                                        <span class="s-navbar"> @User.Identity.Name</span>
                                    </div>
                                </li>
                                <li class="nav-item">
                                    <a class="a-navbar" asp-action="Logout" asp-controller="Accounts"> Logout</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="container">
                @RenderBody()
            </div>
        </div>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="~/lib/popper.js/umd/popper.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/font-awesome/js/all.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/main.js"></script>
    @RenderSection("Scripts", required: false)
    <partial name="_ValidationScriptsPartial" />
</body>
</html>